### ISSUE TITLE
When no question types are added for the new questionnare in QE the questionnare details in list  shows only loading text

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-QuestionEditor#10]
A proper message to guide users to go back and add q types can be implemented as temprory fix

**Comment by onepointpb** [comment]
Currently it is showing as below, which is fine.
![image](https://user-images.githubusercontent.com/26476815/43639830-30bc3742-973b-11e8-8d9f-261d340a7ced.png)
