### ISSUE TITLE
In Live  - Survey preview isnt working because the url is just http and has to be changed to https.

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-QuestionEditor#108]
API    UserQuestionEditor/GetScriptlink    response for the 'TestScriptLink' needs to be changed to https , now its http. becuase of which iframe content isnt loading.

**Comment by vivek-onepoint** [comment]
Hi,

Configuration for the Link is been updated in Live. You can have a look, it should fine now.

**Comment by dougmorris** [comment]
@onepointpb @hitesh-opg

**Comment by hitesh-opg** [comment]
Preview is working as expected in the toolkit
