### ISSUE TITLE
In Custom Theme if we save with duplicate names and apply theme, we are getting tick on both the themes.

### ISSUE THREAD

**Issue by brijeshonepoint** [OnePointGlobal/OnePoint-Global-QuestionEditor#109]
- In Custom Theme if we save with duplicate names and apply theme, we are getting tick on both the themes.
- Also if we save theme name with Theme 1, Theme 2 .... Theme 12 and apply theme we can find tick mark on both the tabs Default and Custom theme.

In get applied theme API we are getting theme name instead if we get theme id then we can match with Id.

**Comment by onepointraj** [comment]
@brijeshonepoint , We will not allow duplicate entry.

**Comment by onepointpb** [comment]
Now it is not allowing to upload theme files with same name.
