### ISSUE TITLE
Unable to save Standard Routing for a free text question

### ISSUE THREAD

**Issue by dougmorris** [OnePointGlobal/OnePoint-Global-QuestionEditor#125]
After having saved a free text question and then attempting to add standard routing it is failing. The screenshot below shows the question:
![image](https://user-images.githubusercontent.com/4094389/59020704-7265bd00-8842-11e9-9734-d7f50e26aac9.png)
When clicking on the Save Button nothing happens.

**Comment by dougmorris** [comment]
I believe this has been fixed now and @shobhitOne can confirm.

**Comment by shobhitOne** [comment]
Tested on Dev and Live, Its working fine.
