### ISSUE TITLE
Need icons for new question types.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#127]
The new question type includes Ranking, Grouping, Image Map, Max Diff etc.

**Comment by dougmorris** [comment]
@onepointpb with Hitesh please choose from the list in this link - https://www.iconfinder.com/iconsets/cc_mono_icon_set

**Comment by dougmorris** [comment]
The icons have been selected, approved and are in development.

**Comment by onepointpb** [comment]
The new icons were implemented and made live.
