### ISSUE TITLE
Need to make Action Alert to work just like the SMS platform.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#129]
It should send notification email based on the responses.

**Comment by dougmorris** [comment]
Action Alert XMl --> Script has been corrected and runtime altered to support blank cc, bcc and from values. Tested on live and works. However macro replacement is not available. This is being worked on now.

**Comment by dougmorris** [comment]
Macro replace is now in place.

**Comment by dougmorris** [comment]
This has been tested by @hitesh-opg and confirmed as working.
