### ISSUE TITLE
Image map question is not moving forward. It is also generating the script with comment box by default. 

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#130]
Image map question is not moving forward. It is also generating the script with comment box by default.

**Comment by dougmorris** [comment]
Changes have been made to XML --> OneScript to include a tag

`<mandatory>true</mandatory> (or false) `

for the imagemap widget to pick up.

**Comment by dougmorris** [comment]
When entries are made in the imagemap question we cannot move forward now.

**Comment by dougmorris** [comment]
The XML --> OneScript has been updated to support `MustAnswer=false` for the whole question now. This has been released for review.

**Comment by dougmorris** [comment]
This has been tested by @hitesh-opg and confirmed as working.
