### ISSUE TITLE
Design Related Queries.

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-QuestionEditor#16]
1. Theme survey - user has no way to know which theme is applied to the questionnaire.
2. Text field variable name feels confusing. Same field name is there even in advanced routing.
3. **Standard routing** Edit - is linked to the question type details , where on edit is doing two things , in standard routing user can also edit the question type which is wrong. We need separate edit for standard routing alone.
4, On click of **Standard routing**  - we can see only list and doesn't give a hint that user has to click on the  accordian to add this feature. It should be up front before the click.
5. Advanced routing - there is no option to cancel the edit operation of a condition and go back to the previous/old  one if user chooses not to continue.
6. Random routing - For selected questions users need to be prompted to select the question types before saving .

**Comment by meghanavbharadwaj** [comment]
1. Will be done.
2. Variable name -  It is the variable for the question. This is similar to the old frame work. Only thing to be considered here is :  Variable name for Advance routing should bot be same as the variable name for the question.
3. The ideology behind this is to make it less complex. It is actually auto edit.The user dont actually have to click on edit icon to edit. This will save a click for the user and a single save button will save routing and question too.
3.4. There is a Routing icon for each question on hover. Please elaborate this.
4. The user can click on the add button to cancel the edit or I will provide a cancel icon
5. This is not implemented in a right way. As soon as the user chooses Random Routing for selected questions, we will show the list of questions and we should have check-boxes for every question instead showing it on hover.

**Comment by meghanavbharadwaj** [comment]
![applied theme design](https://user-images.githubusercontent.com/28921540/43122706-9ad95a28-8f3f-11e8-8a40-466eb65a76d9.png)

1. Design showing Applied Theme

**Comment by onepointpb** [comment]
The designs are implemented as per the comments above.
