### ISSUE TITLE
Preview Script is not updated after the question type is deleted form the list. Same for viewscript

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-QuestionEditor#17]

**Comment by akshatha-opg** [comment]
deleteapi changes is done from api side. while testing found some UI frontend issue brijesh is checking

**Comment by deepika-Gopala** [comment]
@akshatha-opg :  from further testing , issue occurs for both view script and preview script  after a single QT is deleted.
**For Preview :** 
ErrorMessage: "System.NullReferenceException: Object reference not set to an instance of an object.  ↵   at OnePoint.RestApi.Controllers.UserQuestionEditorController.GetScriptlink(Int64 scriptid)"
HttpStatusCode :500

**For ViewScript**
http://apidev.1pt.mobi/V3.0/Api/UserQuestionEditor/GetScriptDetails?scriptId=143283
returns null in the finalScript property.

**Comment by onepointpb** [comment]
Fixed in staging.
