### ISSUE TITLE
Adding question types for the first time saves only first question type. same works second timewhen QE id is there.

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-QuestionEditor#19]
**Also question type doesnt get deleted when question editor id on 0.**

**Comment by akshatha-opg** [comment]
After one save you need to send the questioneditorid but from UI its sending every save questioneditorid  as 0. save api doing insert and update both. so you need to get questioneditorid  from the save response and pass it to second question. 
Due to this it effects database to wrong data saving

**Comment by onepointpb** [comment]
Fixed in staging.
