### ISSUE TITLE
Along with View Script there should be button to download the full project just like the Framework.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#23]
In Framework, we can download a zip file that contains the theme file, script file (should be .one) and the compiled script file.

**Comment by akshatha-opg** [comment]
given api for download script

**Comment by onepointpb** [comment]
The script file present in the export should be of .one format.

**Comment by akshatha-opg** [comment]
Yes we can get .one format also by sending parameter in api like below screen 

![image](https://user-images.githubusercontent.com/29450203/43192823-0ed29a20-901c-11e8-914d-38587fefb493.png)

**Comment by onepointpb** [comment]
This issue is not fixed. It is now downloading only .one file.

**Comment by deepika-Gopala** [comment]
@akshatha-opg  .one type is added in the API response along with other types.

**Comment by akshatha-opg** [comment]
fixed and released api to dev

**Comment by onepointpb** [comment]
fixed in staging.
