### ISSUE TITLE
The "+" icon to add a new Questionnaire should not be displayed inside individual Questionnaire.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#26]
The "+" icon to add a new Questionnaire should not be displayed inside individual Questionnaire.

**Comment by onepointpb** [comment]
After coming out of the questionnaire, go back to the Questionnaire again. Now the plus symbol is not displayed. Hence. it should not be displayed from the first go.

**Comment by onepointraj** [comment]
resolved in local label, need to updated in development server

**Comment by onepointpb** [comment]
The "+" icon to add a new Questionnaire is not displayed inside individual Questionnaire.
