### ISSUE TITLE
The "Mandatory to answer" checkbox should be checked by default for all the questions except Geolocation and Media Upload questions.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#28]
1. The "Mandatory to answer" checkbox should be checked by default for all the questions except Geolocation and Media Upload questions.
2. Change "A" to "a" in "Mandatory to Answer".

**Comment by deepika-Gopala** [comment]
1. RemoveD the default mandatory for geo-location and media upload question from the front end , however from the  backend/runtime scripting these two question types are still mandatory in the preview. @akshatha-opg

**Comment by deepika-Gopala** [comment]
1. Removed the default mandatory for geo-location and media upload question from the front end , this has to be changed from the runtime scripting these two question types are still mandatory in scripting.

**Comment by onepointpb** [comment]
The front-end is done but the script is not updating accordingly.

**Comment by onepointpb** [comment]
Fixed in staging.
