### ISSUE TITLE
While adding a question, the variables are saving in small letters by default.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#30]
1, While adding a question, the variables are getting saved as small letters automatically. It should save as it was entered by the user.
2. In Edit mode, the variables are getting converted into all caps automatically. But after saving again this is getting converted into small letters.

**Comment by akshatha-opg** [comment]
fixed from api side. updated in dev server

**Comment by onepointpb** [comment]
Working now.
