### ISSUE TITLE
After adding standard routing to a question the position of the question is getting changed in Fields section.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#31]
1. After adding standard routing to a question the position of the question is getting changed in Fields section.
2. The generated script is also not correct.

**Comment by akshatha-opg** [comment]
Standard routing condition how UI  sent the xml question order as per that fields get generating.

![image](https://user-images.githubusercontent.com/29450203/42320469-0c003914-8073-11e8-9fc3-9deab6d34ed7.png)

**Comment by onepointpb** [comment]
@akshatha-opg : 
Please check below sample script to understand the issue.
For a questionnaire we are getting different scripts than the existing system.

**Script in existing system:**
Fields { 
Q1 "info test" info;
Q2 "textbox test" text;
Q3 "integer test" long;
}
Main() 
{ 
Interview.LayoutTemplate = "OPG-DefaultTheme.htm"
Q1: 
Q1.ask() 
goto Q3 

Q2: 
Q2.ask() 

Q3: 
Q3.ask() 
} 

**Script generated in new QE:**
Fields { 
Q1 "info test" info;
Q2 "textbox test" text;
Q3 "integer test" long;

}


Main() 
{ 
Interview.LayoutTemplate = "OPG-DefaultTheme.htm"

Q1.ask() 
Q3.ask() 

Q2.ask() 

Q3.ask() 
} 

The new script is causing problem to run the survey.

**Comment by akshatha-opg** [comment]
Issue is fixed and its available in Development server

**Comment by onepointpb** [comment]
Fixed in staging.
