### ISSUE TITLE
The User should be able to add assets when he clicks on Assets floating action button

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-QuestionEditor#44]
Now the User is only able to Upload, Delete assets into Assets Module.
The user should be able to add assets to Questionnaire

**Comment by meghanavbharadwaj** [comment]
We shall remove the Assets option for now and keep only a Question library button under add.

**Comment by onepointpb** [comment]
Adding assets to the Assets module is working in Live.
