### ISSUE TITLE
CSS Issue. Please find the attached image

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-QuestionEditor#46]
![10](https://user-images.githubusercontent.com/28921540/42374591-2fa83f56-8136-11e8-9c97-4db8ca44aa86.png)
![a](https://user-images.githubusercontent.com/28921540/42374654-70c45a24-8136-11e8-84d1-1092f130273d.jpg)

**Comment by onepointpb** [comment]
Now only Choose from Assets option is present.
