### ISSUE TITLE
Advansed routing save shows data retrival failed fromt eh api response.

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-QuestionEditor#47]

**Comment by akshatha-opg** [comment]
Issue is fixed and available in dev server

**Comment by deepika-Gopala** [comment]
Then this error was on any kind of save, which is resolved now.   
However there seems to be a issue related to integer which is linked to #57,  so closing this bug.

**Comment by deepika-Gopala** [comment]
Then this error was on any kind of save, which is resolved now.   
However there seems to be a issue related to integer which is linked to #57,  so closing this bug.
