### ISSUE TITLE
Random Routing - On/Off Icon is not working

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-QuestionEditor#52]
Applied Random Routing and saved.
Now if I click on the Icon- it has to get cancelled and icon should change color. This is not happening.

Also, If I select Random Routing for Selected Questions, it is not getting refreshed

**Comment by onepointpb** [comment]
Working of this feature depends on #96.

**Comment by onepointpb** [comment]
If I click on the Icon - it is not cancelling the random routing and icon color is also not changing. 
If I click on the other options e.g. "All Questions"/"Selected Questions" then it is cancelling the previous random routing being applied.

**Comment by onepointpb** [comment]
Clicking on the icon is now removing the random routing applied.
