### ISSUE TITLE
Matrix Question Type: Not able to add new column. Also there are some UI issue

### ISSUE THREAD

**Issue by meghanavbharadwaj** [OnePointGlobal/OnePoint-Global-QuestionEditor#53]
1. Not able to add new column.

2. Add and delete icon has some CSS issue. Image attached
![002](https://user-images.githubusercontent.com/28921540/42377714-1d8fc184-8142-11e8-9414-14fac92d18c0.jpg)
![09](https://user-images.githubusercontent.com/28921540/42377721-2368f292-8142-11e8-9177-571ad9fb3935.png)

**Comment by dougmorris** [comment]
@onepointpb @hitesh-opg

**Comment by hitesh-opg** [comment]
Matrix question type is working as expected in the Staging and Live toolkit.
