### ISSUE TITLE
API issue - Keywords not accepting numeric value

### ISSUE THREAD

**Issue by brijeshonepoint** [OnePointGlobal/OnePoint-Global-QuestionEditor#57]
In advanced routing keywords are not accepting numeric values. For integer type of questions keywords may contain numbers.

**Comment by akshatha-opg** [comment]
Yes i have checked this issue, its generating script but compilation error in studio. It has to be fixed from compiler side. 
@dougmorris : In advanced routing keywords are not accepting numeric values and NOT  also.

**Comment by dougmorris** [comment]
@akshatha-opg @brijeshonepoint Please can you provide a sample script that you expect to work.

**Comment by akshatha-opg** [comment]
Fields(en-gb, Analysis, Label) {
  intro "Welcome to OneScript" info;
   
   
Q1 "Welcome to Feedback:" info;
Q2 "What is the name of food you had?" text;
Q3 "What is the amount of purchase?" long;
R1 "%{{#Q1.name},{#Q3.name}}" string; 
}


Main() {
    Interview.LayoutTemplate = "prop.htm"
    intro.show()
       

Q1: 
Q1.ask() 

Q2: 
Q2.ask() 

Q3: 
Q3.ask() 


 R1.Response =  R1.Label.Text 
 if R1.response.value.containsany({1,s,sa,sadsad}) then 
  Q2.ask() 
else  
  Q2.ask()  
 
 end if 

}

**Comment by akshatha-opg** [comment]
Kindly refer above advancerouting script

**Comment by dougmorris** [comment]
@akshatha-opg I do not understand what is trying to be achieved with the survey. Can you give an example of the responses and what you would expect please.

**Comment by akshatha-opg** [comment]
In below xml design , advancerouting for condition 1 includes numeric value. once the script genereates it giving error in the following bold line. if we remove numeric then it works well. 

Kindly run the script then you get to know.

R1.Response = R1.Label.Text
**if R1.response.value.containsany({1,s,sa,sadsad}) then**
Q2.ask()
else
Q2.ask()

end if

 <question advancevariablename="R1" questionvariable="R1" sortorder="4">
      <questiontype>string</questiontype>
      <questiontext>Q1,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>AND</name>
            <value1>sadsad</value1>
            <value2>1,s,sa</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect>Q2</redirect>
         </condition>
      </advancerouting>
   </question>

**Comment by akshatha-opg** [comment]
<question advancevariablename="R1" questionvariable="R1" sortorder="4">
      <questiontype>string</questiontype>
      <questiontext>Q1,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>AND</name>
            <value1>sadsad</value1>
            <value2>1,s,sa</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect>Q2</redirect>
         </condition>
      </advancerouting>
   </question>

**Comment by akshatha-opg** [comment]
<question advancevariablename="R1" questionvariable="R1" sortorder="4">
      <questiontype>string</questiontype>
      <questiontext>Q1,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>AND</name>
            <value1>sadsad</value1>
            <value2>1,s,sa</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect>Q2</redirect>
         </condition>
      </advancerouting>
   </question>

**Comment by dougmorris** [comment]
but what out come as you expecting based on R1? Does it have to contain the text SA, S SADSAD or 1 for it to go down the first route?

**Comment by akshatha-opg** [comment]
<question advancevariablename="R1" questionvariable="R1" sortorder="4">
      <questiontype>string</questiontype>
      <questiontext>Q1,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>AND</name>
            <value1>sadsad</value1>
            <value2>1,s,sa</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect>Q2</redirect>
         </condition>
      </advancerouting>
   </question>

**Comment by akshatha-opg** [comment]
It should accept {1,s,sa,sadsad} whole thing inside braket.

**Comment by dougmorris** [comment]
OK. According to OneScript Documentation (http://resources.onepointglobal.com/onescript/home) these are the problems with the script:
1. Q2 is a text field and is "Old Scripting Style". It should be a string field.
2. Q3 is a long field and is "Old Scripting Style". It should be an integer field.
3. In this context enumerators are a list of identifiers seperated by commas and surrounded by curly brackets. Identifiers must start with either a caharacter from A to Z or an underscore and can be folled by either a number from 0 to 9, a character from A to Z or an underscrore. Using {1, at the beginning breaks that basic identifier rule.

If you attempting to string match a result from one value to another then you need use the basic string comparison syntax of the language (e.g. If a = "1" then....) rather than using enumerators to solve this problem. To extend this you would need to use logical connections with the "and" and "or" operators in a conditaionl statement comparing strings. Enumerators are used to check multiple choice options that can be compared with a specific option. The containsany library supports this idea with multiple choice (enumerator) type fields. Do not mix string comparision with enumerator comparision.

**Comment by brijeshonepoint** [comment]
<fields>
   <question variablename="Q1" questionvariable="Q1" sortorder="1">
      <mandatoryans>true</mandatoryans>
      <questiontext>Welcome to Feedback:</questiontext>
      <questiontype>information</questiontype>
      <variablename>Q1</variablename>
   </question>
   <question variablename="Q2" questionvariable="Q2" sortorder="2">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the name of food you had?</questiontext>
      <questiontype>Text Box</questiontype>
      <variablename>Q2</variablename>
   </question>
   <question variablename="Q3" questionvariable="Q3" sortorder="3">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the amount of purchase?</questiontext>
      <questiontype>Integer</questiontype>
      <variablename>Q3</variablename>
   </question>
   <question advancevariablename="R1" questionvariable="R1" sortorder="4">
      <questiontype>string</questiontype>
      <questiontext>Q1,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>AND</name>
            <value1>sadsad</value1>
            <value2>1,s,sa</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect>Q2</redirect>
         </condition>
      </advancerouting>
   </question>
</fields>

**Comment by akshatha-opg** [comment]
Below is the xml format 

<fields>
   <question variablename="Q1" questionvariable="Q1" sortorder="1">
      <mandatoryans>true</mandatoryans>
      <questiontext>Welcome to Feedback:</questiontext>
      <questiontype>information</questiontype>
      <variablename>Q1</variablename>
   </question>
   <question variablename="Q2" questionvariable="Q2" sortorder="2">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the name of food you had?</questiontext>
      <questiontype>Text Box</questiontype>
      <variablename>Q2</variablename>
   </question>
   <question variablename="Q3" questionvariable="Q3" sortorder="3">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the amount of purchase?</questiontext>
      <questiontype>Integer</questiontype>
      <variablename>Q3</variablename>
   </question>
   <question advancevariablename="R1" questionvariable="R1" sortorder="4">
      <questiontype>string</questiontype>
      <questiontext>Q1,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>AND</name>
            <value1>sadsad</value1>
            <value2>1,s,sa</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect>Q2</redirect>
         </condition>
      </advancerouting>
   </question>
</fields>

``

Value 1 and Value 2 are the keywords for Q1 and Q3 respectively where Q3 is integer  and Q1 is text. So we are entering as integer and text.

**Comment by akshatha-opg** [comment]
Kindly check XML format
<fields>
   <question variablename="Q1" questionvariable="Q1" sortorder="1">
      <mandatoryans>true</mandatoryans>
      <questiontext>Welcome to Feedback:</questiontext>
      <questiontype>information</questiontype>
      <variablename>Q1</variablename>
   </question>
   <question variablename="Q2" questionvariable="Q2" sortorder="2">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the name of food you had?</questiontext>
      <questiontype>Text Box</questiontype>
      <variablename>Q2</variablename>
   </question>
   <question variablename="Q3" questionvariable="Q3" sortorder="3">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the amount of purchase?</questiontext>
      <questiontype>Integer</questiontype>
      <variablename>Q3</variablename>
   </question>
   <question advancevariablename="R1" questionvariable="R1" sortorder="4">
      <questiontype>string</questiontype>
      <questiontext>Q1,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>AND</name>
            <value1>sadsad</value1>
            <value2>1,s,sa</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect>Q2</redirect>
         </condition>
      </advancerouting>
   </question>
`</fields>`

**Comment by akshatha-opg** [comment]
<fields>
   <question variablename="Q1" questionvariable="Q1" sortorder="1">
      <mandatoryans>true</mandatoryans>
      <questiontext>Welcome to Feedback:</questiontext>
      <questiontype>information</questiontype>
      <variablename>Q1</variablename>
   </question>
   <question variablename="Q2" questionvariable="Q2" sortorder="2">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the name of food you had?</questiontext>
      <questiontype>Text Box</questiontype>
      <variablename>Q2</variablename>
   </question>
   <question variablename="Q3" questionvariable="Q3" sortorder="3">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the amount of purchase?</questiontext>
      <questiontype>Integer</questiontype>
      <variablename>Q3</variablename>
   </question>
   <question advancevariablename="R1" questionvariable="R1" sortorder="4">
      <questiontype>string</questiontype>
      <questiontext>Q1,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>AND</name>
            <value1>sadsad</value1>
            <value2>1,s,sa</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect>Q2</redirect>
         </condition>
      </advancerouting>
   </question>
</fields>``

**Comment by akshatha-opg** [comment]
<fields>
   <question variablename="Q1" questionvariable="Q1" sortorder="1">
      <mandatoryans>true</mandatoryans>
      <questiontext>Welcome to Feedback:</questiontext>
      <questiontype>information</questiontype>
      <variablename>Q1</variablename>
   </question>
   <question variablename="Q2" questionvariable="Q2" sortorder="2">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the name of food you had?</questiontext>
      <questiontype>Text Box</questiontype>
      <variablename>Q2</variablename>
   </question>
   <question variablename="Q3" questionvariable="Q3" sortorder="3">
      <mandatoryans>true</mandatoryans>
      <questiontext>What is the amount of purchase?</questiontext>
      <questiontype>Integer</questiontype>
      <variablename>Q3</variablename>
   </question>
   <question advancevariablename="R1" questionvariable="R1" sortorder="4">
      <questiontype>string</questiontype>
      <questiontext>Q1,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>AND</name>
            <value1>sadsad</value1>
            <value2>1,s,sa</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect>Q2</redirect>
         </condition>
      </advancerouting>
   </question>
</fields>``

**Comment by dougmorris** [comment]
ok. This is not a compiler error it is a scripting error. As explained above you are using an enumerator library function incorrectly. You need to write a function of your own (in OneScript) for a contains any with strings. We do not currently have one that works only for enumerators.

**Comment by akshatha-opg** [comment]
@dougmorris : please help me out in resolve the scripting error.

**Comment by akshatha-opg** [comment]
Fields(en-gb, Analysis, Label) { 
 
q1 "what is your name?" text;
r1 "%{{#q1.name},{#q3.name}}" string; 
r2 "%{{#q1.name},{#q2.name}}" string; 
q6 "media upload" 
 style(Control(media(AccessGallery=True,AccessNew=True,AllowPlayback=True,AllowUpload=True,MediaType="video")))  
 media; 
r4 "%{{#q1.name},{#q3.name}}" string; 

 }
 
 
Main() 
 { 
Interview.LayoutTemplate = "OPG-DefaultTheme.htm"


q1.ask() 

 r1.Response =  r1.Label.Text 
 if r1.response.value.containsany({option,option,a,s,d,f}) then 
  q2.ask() 

 end if 

 r2.Response =  r2.Label.Text 
 if r2.response.value.containsany({dog,cat,parrot,a,s,d,f}) then 
  q2.ask() 
else  
  q2.ask()  
 
 end if 

q6.ask() 

 r4.Response =  r4.Label.Text 
 if r4.response.value.containsany({i,will,not,tell}) or r4.response.value.containsany({a,d}) then  
  q1.ask() 
else  
  q6.ask()  
 
 end if 

}
