### ISSUE TITLE
conditions are visible as questions in preview after adding advance routing. 

### ISSUE THREAD

**Issue by brijeshonepoint** [OnePointGlobal/OnePoint-Global-QuestionEditor#58]
Routing Conditions are visible as questions in preview after adding advance routing. Below is the script.

Script:

Fields(en-gb, Analysis, Label) { 
 
Q1 "Welcome to Feedback:" info;
Q2 "What is the name of food you had?" text;
Q3 "What is the amount of purchase?" long;
R1 "%{{#Q1.name},{#Q3.name}}" string; 
R2 "%{{#Q1.name},{#Q2.name}}" string; 

 }
 
 
Main() 
 { 
Interview.LayoutTemplate = "OPG-DefaultTheme.htm"

Q1: 
Q1.ask() 

Q2: 
Q2.ask() 
if Q2.Response.value.contains("asdsa ")  or  Q2.Response.value.contains("sadsa ")  or  Q2.Response.value.contains(" asds ")  or  Q2.Response.value.contains("sddds")  or  Q2.Response.value.contains(" sdfds")
 then goto Q1 

Q3: 
Q3.ask() 

R1.ask() 
 R1.Response =  R1.Label.Text 
 if R1.response.value.containsany({a,s,sa,sadsad, sdf, fgdgdf}) then 
  Q2.ask() 
else  
  Q2.ask()  
 
 end if 

R2.ask() 
 R2.Response =  R2.Label.Text 
 if R2.response.value.containsany({sddsf, asds,asdsa}) or R2.response.value.containsany({a, d, d ,fdf}) then  
  Q2.ask() 

 end if 

}

![image](https://user-images.githubusercontent.com/38459171/42613982-6216a1d2-85c1-11e8-98cb-eef91adffdff.png)

**Comment by akshatha-opg** [comment]
Issue is fixed and available in dev server

**Comment by onepointpb** [comment]
Fixed in staging.
