### ISSUE TITLE
Image Preview in assets need to follow aspect ratio, now it looks too steched out.

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-QuestionEditor#59]
![image](https://user-images.githubusercontent.com/19856782/42691820-1ea15bac-86c7-11e8-9327-d61ac37c55ce.png)

**Comment by onepointpb** [comment]
Still the preview is stretched out. It should display the actual size of the image.
![image](https://user-images.githubusercontent.com/26476815/43638287-db9e383c-9735-11e8-960b-6a665617e5c9.png)

**Comment by dougmorris** [comment]
@onepointpb @hitesh-opg

**Comment by onepointpb** [comment]
Now, the images are not stretched in Live.
