### ISSUE TITLE
Can not view the full script in Question editor.

### ISSUE THREAD

**Issue by akshatha-opg** [OnePointGlobal/OnePoint-Global-QuestionEditor#6]
Can not view the full script in Question editor as there is no scroll view.

**Comment by onepointpb** [comment]
Inside a questionnaire the View Script option is having the scroll view, but the Questionnaire list expand view is not having the scroll view.
![image](https://user-images.githubusercontent.com/26476815/43639259-3a11360a-9739-11e8-8a7e-d4f8681be21c.png)

**Comment by onepointpb** [comment]
Scroll view is added.
