### ISSUE TITLE
MCSA jumpto dropdown in standard routing is not working properly.

### ISSUE THREAD

**Issue by deepika-Gopala** [OnePointGlobal/OnePoint-Global-QuestionEditor#60]
On select of ANY item in the options dropdown the jumpto of next option thats behind the dropdown is getting populated with the  selected value instead of  its own dropdown.

**Comment by onepointpb** [comment]
Please refer #93

**Comment by deepika-Gopala** [comment]
Closing this as the issue was raised for the MCSA and is fixed now and is not a duplicate.
