### ISSUE TITLE
Toolkit issues

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-QuestionEditor#67]
-Multiple selection for deleting questionnaire/email templates is not working in Firefox.

-There is no copy option available in questionnaire module.

**Comment by akshatha-opg** [comment]
@onepointraj :api is available in dev server. kindly check below
http://apidev.1pt.mobi/V3.0/api/UserQuestionnaire/CopyQuestionnaire?scriptId=153470

**Comment by dougmorris** [comment]
@hitesh-opg how far is this out of date - as far as I can tell there is no such feature in the platform?

**Comment by hitesh-opg** [comment]
@dougmorris, the issue with Multiple selections for deleting questionnaire/email templates still exits in firefox.

The copy option is now available in the questionnaire module.

**Comment by dougmorris** [comment]
@hitesh-opg I have tested deletions in Firefox and it is working perfectly. Please reconfirm all is ok or not.

**Comment by hitesh-opg** [comment]
This is working now.
