### ISSUE TITLE
Standard routing dropdown is not working for rating question type.  

### ISSUE THREAD

**Issue by brijeshonepoint** [OnePointGlobal/OnePoint-Global-QuestionEditor#72]
Standard routing dropdown is not working for rating question type.  Not able to select values from dropdown.

**Comment by onepointpb** [comment]
Now able to select values but the displayed UI is not correct.
![image](https://user-images.githubusercontent.com/26476815/43636560-0b963ab8-9730-11e8-8d78-27e605ec2614.png)

**Comment by onepointpb** [comment]
Fixed in staging.
