### ISSUE TITLE
Geo-Location question issues

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-QuestionEditor#74]
- Even if the geo-location question is not made mandatory, we are not able to move to next question without answering it.

-In preview the geo-location question gives following message

![location_preview_error](https://user-images.githubusercontent.com/26539946/42876063-25247b50-8aa3-11e8-9924-4a0681083fb8.png)

-In survey the location is displayed as

![location_error_in_survey](https://user-images.githubusercontent.com/26539946/42876086-37a3afee-8aa3-11e8-829b-559b70225007.png)

**Comment by deepika-Gopala** [comment]
#28 

Validation is happening from the script end even  after the value for mandatory is send as false in the XML.

**Comment by brijeshonepoint** [comment]
In script MustAnswer=false is missing which is there in old script

old script : 

`Fields { 
Q1 "fghfghfg" 
style(Control(Type="geocode"))
text; 
Q2 "ghjghj" 
style(Control(Type="geocode"))
text; 

}


Main() 
{ 
Interview.LayoutTemplate = "OPG-DefaultTheme.htm"

Q2.MustAnswer=false

Q1: 
Q1.ask() 

Q2: 
Q2.ask() 

}` 

New script:

`Fields { 
Q1 "fghfghfg" 
style(Control(Type="geocode"))
text; 
Q2 "ghjghj" 
style(Control(Type="geocode"))
text; 

}


Main() 
{ 
Interview.LayoutTemplate = "OPG-DefaultTheme.htm"


Q1: 
Q1.ask() 

Q2: 
Q2.ask() 

}`

**Comment by dougmorris** [comment]
@shobhitOne @brijeshonepoint the script generation works on development. The JavaScript is not working I think.

**Comment by shobhitOne** [comment]
We need to again test the google API and we will get back to you.

**Comment by dougmorris** [comment]
I think we were moving to MapQuest and away from Google Maps

**Comment by hitesh-opg** [comment]
With the latest update(that uses MapQuest) to the toolkit, this issue is resolved.
