### ISSUE TITLE
After applying Advanced routing or Random routing, the script is not getting updated accordingly.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#83]
As a result the advanced routing or random routing is not working at all.

**Comment by onepointpb** [comment]
This is not fixed in staging.

**Comment by brijeshonepoint** [comment]
Issue was due to sending question editor ID as undefined. Fixed that.

**Comment by onepointpb** [comment]
This is fixed except #57 .

**Comment by onepointpb** [comment]
The routing is now applied at the right place in Live.
