### ISSUE TITLE
If standard routing is added to a Textbox question without specifying any keyword then the question is getting removed from the routing part.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#88]
The keyword field in the standard routing for a textbox question is a non-mandatory field. But this is not handled in the routing part.

**Comment by brijeshonepoint** [comment]
It is removing that particular question from the script.

Please check below xml.

`<?xml version="1.0" encoding="UTF-8"?>
<fields>
   <question variablename="Q1" questionvariable="Q1" sortorder="1">
      <questiontext>info</questiontext>
      <questiontype>information</questiontype>
      <variablename>Q1</variablename>
      <questionvariable />
      <mandatoryans>true</mandatoryans>
      <mediatype />
      <mediadisplaytype />
      <mediaid />
      <optionlist />
      <routing />
      <advancerouting />
      <isedit>false</isedit>
      <randomrouting>false</randomrouting>
      <logo>false</logo>
   </question>
   <question variablename="Q2" questionvariable="Q2" sortorder="2">
      <questiontext>text</questiontext>
      <questiontype>Text Box</questiontype>
      <variablename>Q2</variablename>
      <questionvariable />
      <mandatoryans>true</mandatoryans>
      <mediatype />
      <mediadisplaytype />
      <mediaid />
      <optionlist />
      <advancerouting />
      <isedit>false</isedit>
      <randomrouting>true</randomrouting>
      <logo>false</logo>
      <routing>
         <condition id="1">
            <name>contains</name>
            <value />
            <redirect>Q8</redirect>
         </condition>
      </routing>
   </question>
   <question variablename="Q8" questionvariable="Q8" sortorder="3">
      <questiontext>Rating</questiontext>
      <questiontype>Rating</questiontype>
      <variablename>Q8</variablename>
      <questionvariable />
      <mandatoryans>true</mandatoryans>
      <disatisfied />
      <satisfied />
      <maxrange>10</maxrange>
      <minrange>0</minrange>
      <ratingtype>slider</ratingtype>
      <advancerouting />
      <isedit>false</isedit>
      <routing>
         <condition id="1">
            <name>lesserequal</name>
            <value>2</value>
            <redirect>Q3</redirect>
         </condition>
         <condition id="2">
            <name>lesserequal</name>
            <value>3</value>
            <redirect>Q2</redirect>
         </condition>
         <condition id="3">
            <name>lesserequal</name>
            <value>2</value>
            <redirect>Q7</redirect>
         </condition>
         <condition id="4">
            <name>lesserequal</name>
            <value>1</value>
            <redirect>Q3</redirect>
         </condition>
      </routing>
      <randomrouting>false</randomrouting>
      <logo>false</logo>
   </question>
   <question variablename="Q3" questionvariable="Q3" sortorder="4">
      <questiontext>Inte</questiontext>
      <questiontype>Integer</questiontype>
      <variablename>Q3</variablename>
      <questionvariable />
      <mandatoryans>true</mandatoryans>
      <mediatype />
      <mediadisplaytype />
      <mediaid />
      <optionlist />
      <routing />
      <advancerouting />
      <isedit>false</isedit>
      <randomrouting>false</randomrouting>
      <logo>false</logo>
   </question>
   <question variablename="Q5" questionvariable="Q5" sortorder="5">
      <questiontext>MCSA sin</questiontext>
      <questiontype>MCSA</questiontype>
      <variablename>Q5</variablename>
      <questionvariable />
      <mandatoryans>true</mandatoryans>
      <mediatype />
      <mediadisplaytype />
      <mediaid />
      <optionlist>
         <option id="1">
            <labelname>a</labelname>
            <labeltext>sdfdsf</labeltext>
            <mediaid>null</mediaid>
         </option>
         <option id="2">
            <labelname>b</labelname>
            <labeltext>sdfsdf</labeltext>
            <mediaid>null</mediaid>
         </option>
         <option id="3">
            <labelname>c</labelname>
            <labeltext>sdfdsf</labeltext>
            <mediaid>null</mediaid>
         </option>
         <option id="4">
            <labelname>d</labelname>
            <labeltext>sdfsdf</labeltext>
            <mediaid>null</mediaid>
         </option>
      </optionlist>
      <routing />
      <advancerouting />
      <isedit>false</isedit>
      <randomrouting>false</randomrouting>
      <logo>false</logo>
   </question>
   <question variablename="Q6" questionvariable="Q6" sortorder="6">
      <questiontext>geo loc</questiontext>
      <questiontype>Geolocation</questiontype>
      <variablename>Q6</variablename>
      <questionvariable />
      <mandatoryans>false</mandatoryans>
      <mediatype />
      <mediadisplaytype />
      <mediaid />
      <optionlist />
      <routing />
      <advancerouting />
      <isedit>false</isedit>
      <randomrouting>true</randomrouting>
      <logo>false</logo>
   </question>
   <question variablename="Q7" questionvariable="Q7" sortorder="7">
      <questiontext>Bool</questiontext>
      <questiontype>Boolean</questiontype>
      <variablename>Q7</variablename>
      <questionvariable />
      <mandatoryans>true</mandatoryans>
      <mediatype />
      <mediadisplaytype />
      <mediaid />
      <optionlist />
      <advancerouting />
      <isedit>false</isedit>
      <routing>
         <condition id="1">
            <name>lesser</name>
            <value>5</value>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>lesserequal</name>
            <value>4</value>
            <redirect>Q3</redirect>
         </condition>
      </routing>
      <randomrouting>false</randomrouting>
      <logo>false</logo>
   </question>
   <question variablename="Q9" questionvariable="Q9" sortorder="8">
      <mandatoryans>true</mandatoryans>
      <questiontext>Text box new</questiontext>
      <questiontype>Text Box</questiontype>
      <variablename>Q9</variablename>
      <sortorder>9</sortorder>
   </question>
   <question variablename="Q12" questionvariable="Q12" sortorder="9">
      <mandatoryans>true</mandatoryans>
      <questiontext>MCMA</questiontext>
      <questiontype>MCMA</questiontype>
      <variablename>Q12</variablename>
      <sortorder>9</sortorder>
      <optionlist>
         <option id="1">
            <labelname>a</labelname>
            <labeltext>dsfsdf</labeltext>
            <mediaid>null</mediaid>
         </option>
         <option id="2">
            <labelname>b</labelname>
            <labeltext>sdsa</labeltext>
            <mediaid>null</mediaid>
         </option>
         <option id="3">
            <labelname>c</labelname>
            <labeltext>sdfsdf</labeltext>
            <mediaid>null</mediaid>
         </option>
         <option id="4">
            <labelname>d</labelname>
            <labeltext>dfdsfds</labeltext>
            <mediaid>148675</mediaid>
         </option>
      </optionlist>
      <routing>
         <condition id="1">
            <name>contains</name>
            <value>c</value>
            <redirect>Q2</redirect>
         </condition>
      </routing>
   </question>
   <question variablename="Q10" questionvariable="Q10" sortorder="10">
      <mandatoryans>true</mandatoryans>
      <questiontext>currency</questiontext>
      <questiontype>Currency</questiontype>
      <variablename>Q10</variablename>
      <sortorder>10</sortorder>
      <routing>
         <condition id="1">
            <name />
            <value />
            <redirect>Q8</redirect>
         </condition>
      </routing>
   </question>
   <question advancevariablename="R1" questionvariable="R1" sortorder="11">
      <questiontype>string</questiontype>
      <questiontext>Q2,Q3</questiontext>
      <advancerouting>
         <condition id="1">
            <name>OR</name>
            <value1>asdsad</value1>
            <value2>dsad</value2>
            <redirect>Q2</redirect>
         </condition>
         <condition id="2">
            <name>ELSE</name>
            <value1 />
            <value2 />
            <redirect />
         </condition>
      </advancerouting>
   </question>
</fields>
`

**Comment by onepointpb** [comment]
The routing based on keyword is now handled in Advanced routing.
