### ISSUE TITLE
Once the user applies routing and then rearrange some other questions in the questionnaire, then the routing is getting removed in the script.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#90]
Once the user applies routing and then rearrange some other questions in the questionnaire, then the routing is getting removed in the script.

**Comment by deepika-Gopala** [comment]
Have  checked  the xml and it has same routign content before and after rearrange of questions , same XML is shared to @akshatha-opg  to refer and  check.

**Comment by deepika-Gopala** [comment]
Issue is with the additional tag thats gets added on rearrage. Removing additional tags fro the request body keeps the routing and wont remove.

**Comment by onepointpb** [comment]
The routing is not getting removed from the script on rearrange.
