### ISSUE TITLE
Field type for Rating (both slider and star) questions should be integer rather than double.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#91]
Field type for Rating (both slider and star) questions should be integer rather than double.
E.g.
Q1 "slider" 
style(Control(slider(labeltype="label", low="0 ", high="10 "))) integer [0..10 step 1];

Q2 "star" 
style(Control(type="star" )) integer [0..6];

**Comment by dougmorris** [comment]
This has been fixed - please confirm @onepointpb

**Comment by onepointpb** [comment]
This is fixed.
