### ISSUE TITLE
Random routing is not generating the correct script.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-QuestionEditor#96]
The question variables are also not in sync with the actual script. As a result the random routing is not working for both the options (All Questions and Selected Questions).

**Comment by akshatha-opg** [comment]
Fields { 
RandomQuestions "Questions to randomise" enum {
_1 "Q1 1" ,
_2 "Q2 2" ,
_3 "Q3 3" 
 };
}
 
 
Main() 
 { 


Loop : 

Var RandomizeLoop=RondomQuestions.Randomize()

if(RandomizeLoop==null){stop 
}

if(RandomizeLoop=={_1}){ 
Q1.show(); 
goto Loop

};
if(RandomizeLoop=={_2}){ 
Q2.show(); 
goto Loop

};
if(RandomizeLoop=={_3}){ 
Q3.show(); 
goto Loop

};

Above script we are generating it.

and the sample script format is below 

Fields(en-gb, Analysis, Label) {
  intro "Welcome to OneScript" info;
  test "Check Randomize" enum
  {
    _1 "Test 1",
    _2 "test 2"
  };
  
  route1 "route 1" info;
  route2 "route 2" info;
}

Main() {
    Interview.LayoutTemplate = "randomtest.htm"
    intro.show()
    
loop1:
    var a1 = test.Randomize()
    if (a1 == null) {
        stop
    }
    
    if (a1 == {_1}) {
        route1.show();
        goto loop1;
    }
    
    if (a1 == {_2}) {
        route2.show();
        goto loop1;
    }
}

**Comment by akshatha-opg** [comment]
@onepointpb Can you please help on this? As this is a new feature we are not sure how it should work.

And provide some sample script examples.

**Comment by onepointpb** [comment]
@akshatha-opg 

In the above script (which you are generating) there are no questions present. You can not implement the randomisation if no questions are present in the fields part.

Please check the below sample script.

Fields(en-gb, Analysis, Label) {
   intro "Welcome to OneScript" info;
      test "Check Randomize" enum
      {
        _1 "Test 1",
        _2 "test 2",
        _3 "test 3"
      };
  
    Q1 "Info" info;
    Q2 "Textbox" text;
    Q3 "Integer" long;
    
    Q4 "End of survey!" info;
}
Main() {
    Interview.LayoutTemplate = "RandomRouting.htm"
    intro.show()
    
loop1:
    var a1 = test.Randomize()
    if (a1 == null) {
        Q4.show();
    }        
    if (a1 == {_1}) {
        Q1.ask();
        goto loop1;
    }        
    if (a1 == {_2}) {
        Q2.ask();
        goto loop1;
    }
    if (a1 == {_3}) {
        Q3.ask();
        goto loop1;
    }
}

**Comment by onepointpb** [comment]
While saving the random routing getting "Data retrieval failed" error. 
API response is: {"Message":"Failure","ErrorMessage":"There was a problem with the XML Object reference not set to an instance of an object.","HttpStatusCode":500}

The respective XML is:
<Fields>
	<Question VariableName='Q1' QuestionVariable='intro' sortOrder='1'>
		<QuestionType>information</QuestionType>
		<QuestionText>Welcome to OneScript!</QuestionText>
		<MandatoryAns>false</MandatoryAns>
		<RandomRouting>true</RandomRouting>
	</Question>
	<Question VariableName='Q2' QuestionVariable='route1' sortOrder='2'>
		<QuestionType>information</QuestionType>
		<QuestionText>route 1</QuestionText>
		<MandatoryAns>false</MandatoryAns>
		<RandomRouting>true</RandomRouting>
	</Question>
	<Question VariableName='Q3' QuestionVariable='route2' sortOrder='3'>
		<QuestionType>information</QuestionType>
		<QuestionText>route 2</QuestionText>
		<MandatoryAns>false</MandatoryAns>
		<RandomRouting>true</RandomRouting>
	</Question>
	<Question VariableName='Q4' QuestionVariable='route3' sortOrder='4'>
		<QuestionType>information</QuestionType>
		<QuestionText>route 3</QuestionText>
		<MandatoryAns>false</MandatoryAns>
		<RandomRouting>true</RandomRouting>
	</Question>
</Fields>

**Comment by dougmorris** [comment]
@onepointpb this has been fixed on dev and staging.

**Comment by onepointpb** [comment]
This is working in Live.
